apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-health-deployment
  labels:
    app: kube-health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-health
  template:
    metadata:
      labels:
        app: kube-health
    spec:
      containers:
      - name: kube-health
        image: noadespaux31/kube-health:latest
        imagePullPolicy: Always  # For local development
        ports:
        - containerPort: 8181
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: KUBE_HELLO_SERVICE_URL
          value: "http://kube-hello-service:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8181
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8181
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kube-health-service
  labels:
    app: kube-health
spec:
  selector:
    app: kube-health
  ports:
  - name: http
    port: 8181
    targetPort: 8181
    protocol: TCP
  type: ClusterIP
