apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-hello-deployment
  labels:
    app: kube-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-hello
  template:
    metadata:
      labels:
        app: kube-hello
    spec:
      containers:
      - name: kube-hello
        image: noadespaux31/springhello:latest
        imagePullPolicy: Always  # For local development
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: kube-hello-service
  labels:
    app: kube-hello
spec:
  selector:
    app: kube-hello
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort
